import { execFileSync } from 'node:child_process';

/**
 * Git commit attribution for AI-generated code.
 * Tags commits as AI-generated using git trailers.
 */

const AI_TRAILER_KEY = 'Generated-by';
const AI_TRAILER_VALUE = 'FridayCode';

function git(args: string[], cwd: string): string {
  return execFileSync('git', args, { cwd, encoding: 'utf-8' }).trim();
}

/**
 * Create a commit with AI attribution trailer.
 */
export function commitWithAttribution(
  cwd: string,
  message: string,
  options: {
    addAll?: boolean;
    allowEmpty?: boolean;
    author?: string;
  } = {},
): string {
  if (options.addAll) {
    git(['add', '-A'], cwd);
  }

  const fullMessage = `${message}\n\n${AI_TRAILER_KEY}: ${AI_TRAILER_VALUE}`;

  const args = ['commit', '-m', fullMessage];
  if (options.allowEmpty) args.push('--allow-empty');
  if (options.author) args.push('--author', options.author);

  return git(args, cwd);
}

/**
 * Check if a commit was AI-generated by looking for the trailer.
 */
export function isAIGenerated(cwd: string, commitHash: string): boolean {
  try {
    const message = git(['log', '--format=%B', '-n', '1', commitHash], cwd);
    return message.includes(`${AI_TRAILER_KEY}: ${AI_TRAILER_VALUE}`);
  } catch {
    return false;
  }
}

/**
 * Get recent commits with AI attribution info.
 */
export function getRecentCommits(
  cwd: string,
  count: number = 10,
): Array<{
  hash: string;
  message: string;
  author: string;
  date: string;
  aiGenerated: boolean;
}> {
  try {
    const output = git(
      ['log', `--format=%H|%s|%an|%ai`, '-n', String(count)],
      cwd,
    );

    return output.split('\n').filter(Boolean).map((line) => {
      const [hash, message, author, date] = line.split('|');
      return {
        hash,
        message,
        author,
        date,
        aiGenerated: isAIGenerated(cwd, hash),
      };
    });
  } catch {
    return [];
  }
}

/**
 * Get the diff of staged or unstaged changes.
 */
export function getDiff(
  cwd: string,
  options: { staged?: boolean; file?: string } = {},
): string {
  const args = ['diff'];
  if (options.staged) args.push('--staged');
  if (options.file) args.push('--', options.file);
  return git(args, cwd);
}

/**
 * Get the status of the working tree.
 */
export function getStatus(cwd: string): string {
  return git(['status', '--porcelain'], cwd);
}
